package.json
packages/client/getseed.html
packages/client/getseed.js
yarn.lock

- Undo unnecessary package.json and yarn.lock changes.
- Refactor random color selection code.
- Group Tunic and ZA colors so each group uses its own palette.

Random Palette code adjustments

---

Generator/Assets/Items.cs
Generator/Logic/BackendFunctions.cs

- Exclude bug from pool if corresponding Agitha check is excluded. This matches the behavior which has existed in my fork for around a year.

Exclude bug from pool if corresponding Agitha check is excluded

---

Generator/Assets/Checks.cs
Generator/Assets/Items.cs
packages/server/src/server.ts

- Refactor GenerateItemPool
- Add GM key shards to starting items

Refactor GenerateItemPool; add GM key shards to starting items

---

Generator/Assets/Items.cs
Generator/Assets/Rooms.cs
Generator/Logic/SeedGenResults.cs
Generator/Logic/SharedSettings.cs
Generator/Randomizer.cs
packages/client/index.html
packages/client/js/shared.js
packages/client/script.js

- Add setting to prevent small keys on bosses

Add setting to prevent small keys on bosses

---

Generator/Logic/SeedGenResults.cs
Generator/Randomizer.cs
Generator/Util/PlaythroughName.cs
packages/client/getseed.html
packages/client/getseed.js

- Generate seedName for wii which fits within 12 character limit.

Add Wii seedName

---

packages/client/getseed.html

Fix typo 20240214

---

Generator/Assets/Checks.cs
Generator/Assets/Items.cs
Generator/Logic/SharedSettings.cs
Generator/Randomizer.cs
Generator/Util/SettingsEncoder.cs
packages/client/css/style.css
packages/client/index.html
packages/client/js/shared.js
packages/client/script.js
packages/server/src/server.ts

Plando peer review

---

packages/client/index.html

- default ToD to noon
- move No small keys on bosses checkbox to Dungeon Items section

UI adjustments (ToD and No SK on bosses)

---

packages/client/index.html

- Add warning about S+Q to openDot checkbox

Add warning about S+Q to openDot checkbox

---

Generator/Assets/HintDistributions/weak.jsonc
Generator/Hints/HintGenerator.cs

- Update default filler hint behavior
- Add filler hints to any empty custom signs (except skip unrequired barren dungeons since no reason to enter those)

Filler hint changes

---

Generator/Hints/HintGenData.cs
Generator/Logic/CustomMsgData.cs

- Update wallets to preventBarren correctly for not no-logic. Also handle allowBarren checks for wallets.
- Update selfHinters for trap items to display bait items instead of the vanilla item.

Improve selfHinters for trap items; fix wallet preventBarren issues

---

Generator/Translations/Translations.resx

Add missing 's' to Arbiter's Grounds res

---

Generator/Translations/Translations.resx

- Remove extra space in en fem grasshopper res

Remove extra space in en fem grasshopper res

---

Dockerfile
package.json

- Attempt to fix yarn version issues for Dockerfile

Attempt to fix yarn version issues for Dockerfile

---

Generator/Assets/SeedData.cs
Generator/Assets/gci.cs
Generator/Randomizer.cs

- Fix generating output for All region
- For 1.2, only generate files for GC
- Fix issue where GCI header was missing from files for All region

Fix generating output for All region

---

Generator/World/Rooms/Overworld/Eldin Province/Kakariko Village.jsonc

Add ToD logic to the gorons in Kak

---

Generator/Translations/Translations.resx

- Remove space from male mantis en res

Remove space from male mantis en res

---

packages/client/index.html

- Update mirror shard text from 3 to 4

Update mirror shard text from 3 to 4

---

Generator/Translations/Translations.fr.resx
Generator/Translations/Translations.resx

Add res for Red_Potion_Shop

---

Generator/Logic/LogicFunctions.cs
Generator/World/Rooms/Overworld/Faron Province/Hyrule Field - Faron.jsonc
Generator/World/Rooms/Overworld/Lanayru Province/Hyrule Field - Lanayru.jsonc

I added a function for getting hot spring water for the goron in Outside Castle Town South.

Adding canGetHotSpringWater including DM and elde inn springs into glitchless logic

---

Generator/Assets/HintDistributions/season-1.jsonc
Generator/Hints/HintCategory.cs
Generator/Hints/HintCreator/BarrenHintCreator.cs
Generator/Hints/HintCreator/WothHintCreator.cs
Generator/Translations/Translations.fr.resx
Generator/Translations/Translations.resx

- Rename upper and lower desert to southern and northern

Rename upper and lower desert to southern and northern

---

Generator/Hints/HintCategory.cs

Fix AG beyond point

---

Generator/Logic/LogicFunctions.cs

When I deleted something in my branch, it automatically closed the [initial PR](https://github.com/lunarsoap5/Randomizer-Web-Generator-1/pull/56), so I just re-PR'ed it.

Fix hot spring water function

---

Dockerfile
docker-compose.build.yml
packages/build-scripts/deploy.js
stack.yml
start.sh

- Fix various docker issues; install node manually, etc.

Fix various docker issues; install node manually, etc.

---

docs/getting-started.md

- Update getting-started to better explain when you need Docker

Update getting-started to better explain when you need Docker

---

packages/client/js/shared.js

- Sword requirement for ToT was incorrectly set to Master Sword when providing the S1 settings string.
- Version 0 decoding might have had a problem as well, though no one will ever use this and we will eventually increase the minimum version that we support.

Fix ToT settings decode issue for old versions

---

Generator/Logic/CheckIds.cs
Generator/Worker.cs
packages/server/src/server.ts

- Hide certain checks from settings UI (exclusions and plando list)

Hide certain checks from settings UI

---

package.json
packages/client/getseed.js
packages/server/package.json
packages/server/src/server.ts
yarn.lock

- Show different error messages rather than having the page hang.
- Compare seed's imageVer to our current version to see if it is unsupported before trying to parse it (so we can display a better error msg).

Improve error handling on seed page

---

packages/server/src/generationQueues.ts

- Fix exponential growth of queue issue

Fix cancel seedGen queue error

---

Generator/Logic/CustomMsgData.cs
Generator/Logic/CustomMsgUtils.cs
Generator/Translations/Translations.fr.resx
Generator/Translations/Translations.resx
packages/client/js/shared.js

- Allow Coro to self-hint
- Fix issue where we were not sending up the desired language that the user selected

Add Coro to self-hint; fix picking EUR language not working

---

Generator/Logic/CustomMsgData.cs
Generator/Logic/CustomMsgUtils.cs
Generator/Translations/Res.cs
Generator/Translations/Translations.fr.resx
Generator/Translations/Translations.resx

- Show custom text for CT gorons
- Coro now considered shop in the custom text code
- Improve some general resource code

Castle Town goron custom text

---

Generator/Hints/HintGenData.cs
Generator/Translations/Translations.fr.resx
Generator/Translations/Translations.resx

- Update text and hint logic for FW keys for 1.3

Update text and hint logic for FW keys for 1.3

---

Generator/Hints/Hint.cs
Generator/Util/SettingsEncoder.cs
packages/client/js/shared.js

- Update checkIds to use 10 bits instead of 9

Update checkIds to use 10 bits instead of 9
